var TotalCourses = [
    {
        "id": 1,
        "title": "Ielts Witing",
        price: 50,
        "image": "https://i.ibb.co/MsPYwFp/8aed86f64c15bbb88e75032b3ad05139.png",
        "duration": "4 weeks",
        language:"English",
        "instructor":"Mohammad Ali",
    },

    {
        "id": 2,
        "title": "Ielts Academic Test",
        "price": 60,
        "image": "https://i.ibb.co/yVRxFPm/Free-British-Council-IELTS-Preparation-Online.jpg",
        "duration": "6 weeks",
        language:"English",
        "instructor":"Jay",
    },

    {
        "id": 3,
        "title": "Basic Programming",
        price: 40,
        "image": "https://i.ibb.co/3k29qNP/Basic-programming.jpg",
        "duration": "8 weeks",
        language:"English",
        "instructor":"Mohammad Jamshed",
    },

    {
        "id": 4,
        "title": "E-commerce website",
        price: 30,
        "image": "https://i.ibb.co/z4pvDfw/E-commerce-website-banner.jpg",
        "duration": "2 weeks",
        language:"Bengali",
        "instructor":"Mohammad Nayem",
    },

    {
        "id": 5,
        "title": "Ielts Preparation",
        price: 50,
        "image": "https://i.ibb.co/G7NPkxX/ielts-preparation.jpg",
        "duration": "8 weeks",
        language:"English",
        "instructor":"Mohammad Billah",
    },

    {
        "id": 6,
        "title": "Ielts Preparation Free Course",
        price: 0,
        "image": "https://i.ibb.co/XpR1dxQ/Ielts-reading.png",
        "duration": "4 weeks",
        language:"English",
        "instructor":"Mohammad Ali",
    },

    {
        "id": 7,
        "title": "Computer Basic Course",
        price: 50,
        "image": "https://i.ibb.co/6Dr985F/images.jpg",
        "duration": "10 weeks",
        language:"English",
        "instructor":"Suman paul",
    },

    {
        "id": 8,
        "title": "Web Design and Development",
        price: 60,
        "image": "https://i.ibb.co/Jy80kLt/images.png",
        "duration": "12 weeks",
        language:"English",
        "instructor":"Mohammad Zaman",
    },

    {
        "id": 9,
        "title": "Mastering Ielts",
        price: 40,
        "image": "https://i.ibb.co/RjShTrY/Mastering-ielts.jpg",
        "duration": "4 weeks",
        language:"English",
        "instructor":"Mohammad Fahad",
    },

    {
        "id": 10,
        "title": "Microsoft Office Courses",
        price: 40,
        "image": "https://i.ibb.co/RQBBYkj/Microsoft-Office-Course.jpg",
        "duration": "4 weeks",
        language:"English",
        "instructor":"Mohammad Kamal",
    },
    {
        "id": 11,
        "title": "Microsoft Excel",
        price: 0,
        "image": "https://i.ibb.co/cLw6w1D/online-study.jpg",
        "duration": "4 weeks",
        language:"English",
        "instructor":"Mohammad Ali",
    },
    {
        "id": 12,
        "title": "Python Learning",
        price: 30,
        "image": "https://i.ibb.co/LxkRbTx/Python.jpg",
        "duration": "4 weeks",
        language:"English",
        "instructor":"Mohammad Khan",
    },
    {
        "id": 13,
        "title": "SQL Learning",
        price: 11,
        "image": "https://i.ibb.co/4J04bsT/SQL.jpg",
        "duration": "4 weeks",
        language:"Bengali",
        "instructor":"Mohammad Mahabub",
    },
    {
        "id": 14,
        "title": "Responsive Web Design",
        price: 50,
        "image": "https://i.ibb.co/HKyV09R/web-development-in-2016.jpg",
        "duration": "4 weeks",
        language:"English",
        "instructor":"Mohammad Ali",
    },
    {
        "id": 15,
        "title": "WordPress",
        price: 40,
        "image": "https://i.ibb.co/WxZXf3k/wordpress.jpg",
        "duration": "4 weeks",
        language:"English",
        "instructor":"Mohammad Sohag",
    },
]

export default TotalCourses;